# Generated by Django 6.0 on 2025-12-18 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('valid_from', models.DateTimeField(verbose_name='Válido de')),
                ('valid_to', models.DateTimeField(verbose_name='Válido até')),
                ('discount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usage_count', models.IntegerField(default=0, verbose_name='Vezes Usado')),
            ],
        ),
    ]
