# Generated by Django 5.2.8 on 2025-11-30 17:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('discount_percent', models.IntegerField(help_text='Porcentagem de desconto (0 a 100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto (%)')),
                ('active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('valid_from', models.DateTimeField(auto_now_add=True, verbose_name='Válido de')),
                ('valid_to', models.DateTimeField(blank=True, null=True, verbose_name='Válido até')),
            ],
        ),
    ]
