# Generated by Django 6.0 on 2026-01-06 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_coupon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupon',
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={},
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='created_at',
            new_name='date_enrolled',
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(default='paid', max_length=20),
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='asaas_customer_id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='asaas_payment_id',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='asaas_payment_link',
        ),
    ]
