# Generated by Django 5.2.8 on 2025-11-26 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.ImageField(blank=True, help_text='Envie uma imagem (JPG/PNG) tamanho A4 paisagem para ser o fundo', null=True, upload_to='certificate_templates/'),
        ),
    ]
