# Generated by Django 5.2.8 on 2025-11-26 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_certificate_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Assunto da Live')),
                ('meet_link', models.URLField(verbose_name='Link do Meet')),
                ('date_time', models.DateTimeField(verbose_name='Data e Hora')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='courses.course')),
            ],
            options={
                'verbose_name': 'Aula ao Vivo',
                'verbose_name_plural': 'Aulas ao Vivo',
                'ordering': ['date_time'],
            },
        ),
    ]
