# Generated by Django 5.2.8 on 2025-11-30 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_lessonview'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Título do Material')),
                ('file', models.FileField(upload_to='course_materials/', verbose_name='Arquivo')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.lesson')),
            ],
            options={
                'verbose_name': 'Material Complementar',
                'verbose_name_plural': 'Materiais Complementares',
            },
        ),
    ]
