# Generated by Django 6.0 on 2025-12-18 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_coupon_order_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDashboard',
            fields=[
            ],
            options={
                'verbose_name': 'Dashboard de Vendas',
                'verbose_name_plural': 'Dashboard de Vendas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
