# Generated by Django 6.0 on 2026-01-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderdashboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=2, unique=True, verbose_name='Estado (UF)')),
                ('pac_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo PAC')),
                ('pac_days', models.PositiveIntegerField(verbose_name='Prazo PAC (dias)')),
                ('sedex_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo SEDEX')),
                ('sedex_days', models.PositiveIntegerField(verbose_name='Prazo SEDEX (dias)')),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Custo Transportadora')),
                ('delivery_days', models.PositiveIntegerField(verbose_name='Prazo Transportadora (dias)')),
            ],
            options={
                'verbose_name': 'Tabela de Frete',
                'verbose_name_plural': 'Tabelas de Fretes',
            },
        ),
    ]
