# Generated by Django 6.0 on 2026-01-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_state_alter_order_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(choices=[('pac', 'PAC'), ('sedex', 'SEDEX'), ('delivery', 'Transportadora')], default='pac', max_length=20, verbose_name='Método de Envio'),
        ),
    ]
