# Generated by Django 6.0 on 2026-01-06 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_shipping_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(14, message='O WhatsApp deve estar no formato (00) 00000-0000')]),
        ),
    ]
