# Generated by Django 6.0 on 2026-01-06 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(15, message='O número de WhatsApp está incompleto.')], verbose_name='WhatsApp'),
        ),
    ]
