# Generated by Django 6.0 on 2026-01-06 11:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, message='O CEP deve conter 8 dígitos.')], verbose_name='CEP'),
        ),
    ]
