# Generated by Django 6.0 on 2026-01-06 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_alter_order_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processing', 'Em Separação'), ('shipped', 'Enviado / Em Trânsito'), ('delivered', 'Entregue')], default='processing', max_length=20, verbose_name='Status da Entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código de Rastreio'),
        ),
    ]
