# Generated by Django 6.0 on 2026-01-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_orderitem_course_alter_orderitem_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCourse',
            fields=[
            ],
            options={
                'verbose_name': 'Inscrição de Curso',
                'verbose_name_plural': '🎓 Pedidos: Cursos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
        migrations.CreateModel(
            name='OrderWine',
            fields=[
            ],
            options={
                'verbose_name': 'Pedido de Vinho',
                'verbose_name_plural': '🛒 Pedidos: Vinhos',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('orders.order',),
        ),
    ]
