# Generated by Django 6.0 on 2026-01-07 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_ordercourse_orderwine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(11, message='O número de WhatsApp está incompleto.')], verbose_name='WhatsApp'),
        ),
    ]
