# Generated by Django 6.0 on 2026-02-01 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_order_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(default='S/N', max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
    ]
