# Generated by Django 6.0 on 2026-02-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_order_complement_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingrate',
            name='delivery_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo Transportadora'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='delivery_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo Transportadora (dias)'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='pac_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo PAC'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='pac_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo PAC (dias)'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='sedex_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Custo SEDEX'),
        ),
        migrations.AlterField(
            model_name='shippingrate',
            name='sedex_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Prazo SEDEX (dias)'),
        ),
    ]
