# Generated by Django 6.0 on 2025-12-17 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(upload_to='products/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destaque na Home')),
                ('is_promotion', models.BooleanField(default=False, verbose_name='Promoção')),
                ('grape', models.CharField(blank=True, max_length=100, verbose_name='Uva')),
                ('vintage', models.PositiveIntegerField(blank=True, null=True, verbose_name='Safra')),
                ('winery', models.CharField(blank=True, max_length=255, verbose_name='Vinícola')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='País')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Região')),
                ('alcohol_content', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Teor Alcoólico')),
                ('volume', models.CharField(blank=True, default='750ml', max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.category')),
            ],
        ),
    ]
