# Generated by Django 6.0 on 2026-01-07 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_image_course_is_active'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_course',
            field=models.ForeignKey(blank=True, help_text='Se este produto for um curso, selecione-o aqui para liberação automática.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course', verbose_name='Curso Vinculado'),
        ),
    ]
